# frozen_string_literal: true

# CustomerMessagePublisher
#
# Publishes a customer message to the Reliability Lab event pipeline.
#
# This is an INTEGRATION EXAMPLE showing how a Rails application (monolith or
# microservice) could produce events consumed by the Python reliability pipeline.
#
# Design decisions:
# - message_id is generated by the CALLER (Rails app) and passed to the pipeline.
#   This is the idempotency key — if the HTTP call times out, the caller can
#   safely retry with the same message_id.
# - The service returns a Result object, not raises exceptions. This lets the
#   caller decide how to handle failures (retry, log, dead-letter, etc.).
# - Timeout is set to 5 seconds. The pipeline returns 202 Accepted immediately
#   after publishing to RabbitMQ, so this should be fast. If it's not, something
#   is wrong and the caller should not block.
#
# Usage:
#   result = CustomerMessagePublisher.call(
#     customer_id: "cust-001",
#     text: "مرحبا بالعالم",
#     channel: "web",
#     message_id: SecureRandom.uuid
#   )
#
#   if result.success?
#     Rails.logger.info "Published #{result.message_id}"
#   else
#     Rails.logger.error "Publish failed: #{result.error}"
#   end

require "net/http"
require "json"
require "uri"

class CustomerMessagePublisher
  # Configuration — in a real Rails app, these would come from
  # Rails.application.config or environment variables.
  API_BASE_URL = ENV.fetch("RELIABILITY_LAB_API_URL", "http://localhost:8000")
  API_TIMEOUT  = 5 # seconds

  # Structured result object — cleaner than returning [success, payload] arrays.
  Result = Struct.new(:success, :message_id, :error, :status_code, keyword_init: true) do
    def success?
      success
    end

    def duplicate?
      status_code == 200
    end
  end

  # Public entry point.
  #
  # @param customer_id [String]  external customer identifier
  # @param text        [String]  message body (Arabic or any UTF-8)
  # @param channel     [String]  origin channel ("web", "mobile", "api", etc.)
  # @param message_id  [String]  UUID v4 — idempotency key (caller MUST provide)
  # @return [Result]
  def self.call(customer_id:, text:, channel:, message_id:)
    new(customer_id, text, channel, message_id).call
  end

  def initialize(customer_id, text, channel, message_id)
    @customer_id = customer_id
    @text        = text
    @channel     = channel
    @message_id  = message_id
  end

  def call
    uri  = build_uri
    http = build_http(uri)
    req  = build_request(uri)

    response = http.request(req)

    case response.code.to_i
    when 202
      # Accepted — message published to RabbitMQ successfully
      Result.new(success: true, message_id: @message_id, status_code: 202)
    when 200
      # OK — duplicate message (idempotency worked)
      Result.new(success: true, message_id: @message_id, status_code: 200)
    when 422
      # Unprocessable — validation error (malformed payload)
      body = safe_parse(response.body)
      Result.new(success: false, message_id: @message_id, status_code: 422,
                 error: body.fetch("detail", "Validation error"))
    when 503
      # Service Unavailable — Redis or RabbitMQ down
      Result.new(success: false, message_id: @message_id, status_code: 503,
                 error: "Pipeline unavailable (Redis or RabbitMQ down)")
    else
      Result.new(success: false, message_id: @message_id,
                 status_code: response.code.to_i,
                 error: "Unexpected response: #{response.code}")
    end
  rescue Net::OpenTimeout, Net::ReadTimeout
    # ⚠️  RETRY CAUTION:
    # The HTTP call timed out, but the message MAY have been published.
    # Because we use message_id for idempotency, it is SAFE to retry with
    # the SAME message_id. The pipeline will detect the duplicate and return
    # 200 instead of 202.
    #
    # Do NOT retry with a NEW message_id — that would create a duplicate.
    Result.new(success: false, message_id: @message_id,
               error: "Timeout after #{API_TIMEOUT}s — retry with same message_id is safe")
  rescue StandardError => e
    Result.new(success: false, message_id: @message_id,
               error: "Connection error: #{e.message}")
  end

  private

  def build_uri
    URI.join(API_BASE_URL, "/api/v1/messages")
  end

  def build_http(uri)
    Net::HTTP.new(uri.host, uri.port).tap do |http|
      http.open_timeout = API_TIMEOUT
      http.read_timeout = API_TIMEOUT
      http.use_ssl     = (uri.scheme == "https")
    end
  end

  def build_request(uri)
    Net::HTTP::Post.new(uri).tap do |req|
      req["Content-Type"] = "application/json"
      req["Accept"]       = "application/json"
      req.body = JSON.generate({
        message_id:  @message_id,
        customer_id: @customer_id,
        text:        @text,
        channel:     @channel
      })
    end
  end

  def safe_parse(body)
    JSON.parse(body)
  rescue JSON::ParserError
    {}
  end
end

# ─────────────────────────────────────────────────────────
# Example: Rails background job wrapper (Sidekiq)
# ─────────────────────────────────────────────────────────
#
# class PublishMessageJob
#   include Sidekiq::Job
#
#   def perform(customer_id, text, channel, message_id)
#     result = CustomerMessagePublisher.call(
#       customer_id: customer_id,
#       text: text,
#       channel: channel,
#       message_id: message_id
#     )
#
#     unless result.success?
#       # Retry with the SAME message_id (idempotency-safe)
#       raise PublishFailed, result.error
#     end
#   end
# end

# ─────────────────────────────────────────────────────────
# Example: Circuit breaker wrapper (Semian)
# ─────────────────────────────────────────────────────────
#
# class CustomerMessagePublisher
#   extend Semian::Resource
#
#   # Trip after 5 failures in 60s, half-open after 30s
#   semian_configuration(
#     name: "reliability_lab_api",
#     tickets: 3,
#     success_threshold: 2,
#     error_threshold: 5,
#     error_timeout: 60,
#     half_open_resource_timeout: 30
#   )
#
#   def call
#     Semian[:reliability_lab_api].acquire do
#       # ... existing HTTP call logic ...
#     end
#   end
# end
